In [4]:
# 1.

In [1]:
from classroom import Person, Student

In [19]:
me = Person('Benedikt', 'Daurer') 

In [2]:
me = Student('Benedikt', 'Daurer', 'physics') 

In [3]:
me.fullname_sub() 

BenediktDaurer studying in physics


In [5]:
# 2. 

In [6]:
import numpy as np

In [9]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
c = np.random.rand(10)
print(c)
c = c[::-1]
c

[0.07737668 0.14271986 0.58379533 0.29725885 0.18691967 0.00553968
 0.45113412 0.307173   0.15376651 0.35683015]


array([0.35683015, 0.15376651, 0.307173  , 0.45113412, 0.00553968,
       0.18691967, 0.29725885, 0.58379533, 0.14271986, 0.07737668])

In [19]:
d = np.arange(0,9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
e = np.array([1,2,0,0,4,0])
e2= e!=0
e3 = np.where(e2)
e3

(array([0, 1, 4]),)

In [39]:
f = np.random.random(30)
print(f)
print(np.mean(f))

[0.08201095 0.39836921 0.79935203 0.55919818 0.94962155 0.53395239
 0.05096434 0.95490438 0.7292288  0.12031925 0.69174399 0.76982521
 0.12455452 0.71211082 0.28576686 0.54138091 0.19116612 0.06620927
 0.6516916  0.30194428 0.19710865 0.98321823 0.74547664 0.90741644
 0.27357484 0.645809   0.0253466  0.05778183 0.26801871 0.44409037]
0.4687385327262248


In [54]:
n = 3
g = np.ones([n,n])
g[1,1]= 0
g

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [75]:
# i
# Create an 8x8 matrix filled with zeros
checkerboard_matrix = np.zeros((8, 8), dtype=int)

# Set alternate elements to 1 to create the checkerboard pattern
checkerboard_matrix[1::2, ::2] = 1  # Odd rows, even columns
checkerboard_matrix[::2, 1::2] = 1  # Even rows, odd columns
checkerboard_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [76]:
j = np.arange(11)
print(j)
j[3:8]=-1*j[3:8]
print(j)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [78]:
k = np.random.random(10)
print(k)
k = np.sort(k)
print(k)

[0.96866842 0.24130982 0.49451848 0.22160247 0.48939213 0.8549392
 0.18049982 0.3516066  0.34959061 0.35164957]
[0.18049982 0.22160247 0.24130982 0.34959061 0.3516066  0.35164957
 0.48939213 0.49451848 0.8549392  0.96866842]


In [80]:
i1 = np.random.randint(0,2,5)
i2 = np.random.randint(0,2,5)
print(i1,i2)
equal = i1==i2
print(equal)

[1 0 1 0 0] [1 0 0 1 0]
[ True  True False False  True]


In [83]:
m = np.arange(10, dtype=np.int32)
print(m.dtype)
m = m.astype(np.float32)
print(m.dtype)

int32
float32


In [88]:
n1 = np.arange(9).reshape(3,3)
print(n1)
n2 = n1 + 1
print(n2)
n3 = np.dot(n1,n2)
print(n3)
n4 = np.diagonal(n3)
print(n4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]


In [89]:
# 3
a = np.random.random((1000000))
b = list(a)

In [90]:
%timeit a.sum()

185 µs ± 227 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [91]:
%timeit sum(b)

41 ms ± 270 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
import numpy as np

In [99]:
N = 250
X = np.random.randint(0, 100, (N,N+1) )
X.shape

(250, 251)

# Ad Exe

In [1]:
XYZ = [[1.0, 2.0, 10],
 [3.0, 4.0, 20],
 [5.0, 6.0, 30],
 [7.0, 8.0, 40]]
XYZ = np.array(XYZ)

In [10]:
XYZ_n = XYZ/XYZ[:,2][:, np.newaxis]
XYZ_n

array([[0.1       , 0.2       , 1.        ],
       [0.15      , 0.2       , 1.        ],
       [0.16666667, 0.2       , 1.        ],
       [0.175     , 0.2       , 1.        ]])

In [16]:
ad_b = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 6.0],
                [7.0, 8.0, 9.0]])
n = [0,1,2] # np.arange(3)
ad_b2 = ad_b[[0,1,2],n]#ad_b[n,n]
ad_b2

array([1., 5., 9.])

In [39]:
ad_c = np.random.rand(10,3)
print(ad_c)
ad_c2 = np.abs(ad_c-0.75)
print(ad_c2)
ad_c3 = np.argmin(ad_c2, axis =1)
print(ad_c3)
ad_c4 = ad_c[np.arange(10),ad_c3] #
ad_c4

[[0.89444363 0.86266667 0.42295712]
 [0.46719113 0.0268475  0.56848079]
 [0.52903068 0.38673232 0.74894523]
 [0.90152315 0.9826787  0.67276395]
 [0.56852088 0.84214621 0.08167722]
 [0.31566566 0.29173595 0.49435568]
 [0.29222208 0.8357777  0.13855153]
 [0.29971147 0.30784781 0.20350246]
 [0.42680551 0.72422164 0.93936465]
 [0.92128384 0.90669035 0.80331474]]
[[0.14444363 0.11266667 0.32704288]
 [0.28280887 0.7231525  0.18151921]
 [0.22096932 0.36326768 0.00105477]
 [0.15152315 0.2326787  0.07723605]
 [0.18147912 0.09214621 0.66832278]
 [0.43433434 0.45826405 0.25564432]
 [0.45777792 0.0857777  0.61144847]
 [0.45028853 0.44215219 0.54649754]
 [0.32319449 0.02577836 0.18936465]
 [0.17128384 0.15669035 0.05331474]]
[1 2 2 2 1 2 1 1 1 2]


array([0.86266667, 0.56848079, 0.74894523, 0.67276395, 0.84214621,
       0.49435568, 0.8357777 , 0.30784781, 0.72422164, 0.80331474])

In [40]:
x = np.empty((10, 8, 6))

idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)

x[idx0, idx1, idx2]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
x = np.arange(12, dtype=np.int32).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)